version: "3.0"
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
  backend:
    build: backend
    ports:
      - "80:80"
  frontend:
    build: frontend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
